### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by mesqueeb** [corinzio/cordova-plugin-google-signin#1]
I've been trying to use the famous [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) but I keep getting an error 16, so I'm considering of switching to your plugin!

Is it still active? Does it still work for you?

**Comment by corinzio** [comment]
Hello, i don't use Cordova anymore (and this plugin was only for android) so the project is not active, but after i wrote this cordova-plugin-googleplus android version was updated by PointSource so i think that version was better, which scopes do you ask for (plus.me plus.login are [deprecated](https://developers.google.com/identity/sign-in/web/quick-migration-guide) now) ?

if you want you can give it a try it should be quite easy to test it following the instructions in the readme.md

let me know if you need some other info.
Luca

**Comment by corinzio** [comment]
I can confirm that using cordova 7.1 the plugin still works:
![cattura](https://user-images.githubusercontent.com/974603/50729576-bd1cc500-113c-11e9-8822-e2810f97394b.JPG)

**Comment by mesqueeb** [comment]
Great!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
